#!/usr/bin/env python3
"""KaggleCompute connector: the submit/status/download interface.

Runs on any machine with the Kaggle CLI authenticated (~/.kaggle/kaggle.json).
External systems integrate through these commands (contract: CONNECTOR.md).

  connector.py submit   --job job.yaml
  connector.py status   --job-id <id>
  connector.py download --job-id <id> [--dest ./out]
  connector.py ledger
"""
import argparse
import base64
import io
import json
import os
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
KERNEL_PKG = ["runner/run.py", "runner/ledger.py"]  # + the job's profile dir


def eprint(*a):
    print(*a, file=sys.stderr)


def bundle(profile_name):
    """Zip the runner + one profile into a self-contained base64 payload."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for rel in KERNEL_PKG:
            z.write(REPO_ROOT / rel, rel)
        pdir = REPO_ROOT / "profiles" / profile_name
        for f in sorted(pdir.rglob("*")):
            if f.is_file():
                z.write(f, f.relative_to(REPO_ROOT))
    return base64.b64encode(buf.getvalue()).decode()


def kaggle_user():
    cfg = Path.home() / ".kaggle" / "kaggle.json"
    if not cfg.exists():
        eprint("ERROR: ~/.kaggle/kaggle.json not found - see docs/kaggle-setup.md")
        sys.exit(4)
    return json.loads(cfg.read_text())["username"]


def load_job(path):
    job = yaml.safe_load(Path(path).read_text())
    job_id = job.get("job_id", "")
    if not job_id or not all(c.isalnum() or c == "-" for c in job_id):
        eprint("ERROR: job_id required, [a-z0-9-] only")
        sys.exit(2)
    profile = job.get("profile", "")
    if not (REPO_ROOT / "profiles" / profile / "profile.yaml").exists():
        eprint(f"ERROR: unknown profile '{profile}'")
        sys.exit(2)
    return job


def profile_needs_gpu(profile_name):
    p = yaml.safe_load((REPO_ROOT / "profiles" / profile_name / "profile.yaml").read_text())
    return any(s.get("gpu") for s in p.get("stages", []))


RUN_JOB_TEMPLATE = '''\
# Auto-generated by KaggleCompute connector. Self-contained job kernel.
import base64, io, json, subprocess, sys, zipfile
from pathlib import Path

BUNDLE = """{bundle}"""
JOB_YAML = """{job_yaml}"""

work = Path("/kaggle/working" if Path("/kaggle/working").exists() else ".")
root = work / "kc-pkg"
root.mkdir(parents=True, exist_ok=True)
with zipfile.ZipFile(io.BytesIO(base64.b64decode(BUNDLE))) as z:
    z.extractall(root)
(root / "job.yaml").write_text(JOB_YAML)
profile_dir = root / "profiles" / {profile!r}
sys.exit(subprocess.call([
    sys.executable, str(root / "runner" / "run.py"),
    "--profile", str(profile_dir), "--job", str(root / "job.yaml"),
]))
'''


def cmd_submit(args):
    job = load_job(args.job)
    job_id, profile = job["job_id"], job["profile"]
    user = kaggle_user()
    needs_gpu = profile_needs_gpu(profile)

    config_path = REPO_ROOT / "config" / "farm.config.yaml"
    accelerator = None
    if config_path.exists():
        cfg = yaml.safe_load(config_path.read_text())
        accelerator = cfg.get("kaggle", {}).get("default_accelerator")

    job_yaml = Path(args.job).read_text()
    dataset_sources = []
    input_ds = (job.get("params") or {}).get("input_dataset")
    if input_ds:
        dataset_sources.append(input_ds)

    with tempfile.TemporaryDirectory() as d:
        d = Path(d)
        (d / "run_job.py").write_text(RUN_JOB_TEMPLATE.format(
            bundle=bundle(profile), job_yaml=job_yaml, profile=profile))
        metadata = {
            "id": f"{user}/kc-{job_id}",
            "title": f"KC {job_id}",
            "code_file": "run_job.py",
            "language": "python",
            "kernel_type": "script",
            "is_private": True,
            "enable_gpu": needs_gpu,
            "enable_internet": True,
            "dataset_sources": dataset_sources,
            "competition_sources": [],
            "kernel_sources": [],
        }
        (d / "kernel-metadata.json").write_text(json.dumps(metadata, indent=1))
        cmd = ["kaggle", "kernels", "push", "-p", str(d)]
        if needs_gpu and accelerator:
            cmd += ["--accelerator", accelerator]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0:
            eprint(proc.stdout, proc.stderr)
            eprint("NOTE: for T4x2, enable it once on the web first (docs/kaggle-setup.md)")
            sys.exit(4)
        print(proc.stdout.strip())
    print(json.dumps({"job_id": job_id, "kernel": f"{user}/kc-{job_id}",
                      "status": "submitted", "gpu": needs_gpu}))


def cmd_status(args):
    user = kaggle_user()
    kid = f"{user}/kc-{args.job_id}"
    subprocess.run(["kaggle", "kernels", "status", kid])
    with tempfile.TemporaryDirectory() as d:
        proc = subprocess.run(["kaggle", "kernels", "output", kid, "-p", d, "--quiet"],
                              capture_output=True, text=True)
        manifest = Path(d) / args.job_id / "job-manifest.json"
        if not manifest.exists():
            manifest = Path(d) / "job-manifest.json"
        if manifest.exists():
            print("\n--- job manifest ---")
            print(manifest.read_text())
        elif proc.returncode != 0:
            print("(no job output yet - kernel still queued or early in run)")


def cmd_download(args):
    user = kaggle_user()
    dest = Path(args.dest)
    dest.mkdir(parents=True, exist_ok=True)
    subprocess.run(["kaggle", "kernels", "output", f"{user}/kc-{args.job_id}",
                    "-p", str(dest)])


def cmd_ledger(_args):
    local = Path("ledger.json")
    if local.exists():
        sys.path.insert(0, str(REPO_ROOT / "runner"))
        import ledger as lg
        print(lg.report(local))
    else:
        print("no local ledger.json; ledgers live inside each job session "
              "(sync via the kagglecompute-state dataset when configured)")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("submit"); s.add_argument("--job", required=True); s.set_defaults(fn=cmd_submit)
    s = sub.add_parser("status"); s.add_argument("--job-id", required=True); s.set_defaults(fn=cmd_status)
    s = sub.add_parser("download"); s.add_argument("--job-id", required=True)
    s.add_argument("--dest", default="./kc-out"); s.set_defaults(fn=cmd_download)
    s = sub.add_parser("ledger"); s.set_defaults(fn=cmd_ledger)
    args = ap.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
